web: python manage.py makemigrations ftl_app
web: python manage.py sqlmigration ftl_app 0001
web: python manage.py sqlmigration ftl_app 0002
web: python manage.py migrate
web: gunicorn fynd_imdb_site.wsgi